### PR TITLE
SiteMapServlet - Assets to resource visitor

### PR DESCRIPTION
**Pull request by davidjgonzalez**
WDYT about using a resource visitor to walk the tree per the discussion on the ACS Commons GH PR?

Basically just moved your code around alittle..

### CODE REVIEW

**Comment by HitmanInWis** [comment]
Hi David,

Can you help me understand the motivation for the change to use the Visitor?  I agree that it is a use case that can fit use of Visitor, but I'm not sure i see a clear benefit to the change.

As would be expected by any code abstraction such as the Visitor, the visitor code is a little less straight-forward and simple - the new code is over 50% larger to accomplish the same task as before and has more abstraction.  In addition, the site Pages are still written to the sitemap without using the visitor, so now we have two very distinct patterns of adding items to the sitemap in this same servlet.

I think the Resource Visitor is a good pattern, and the tradeoffs balanced by maintainability benefits in many cases, but I'm not seeing the benefits in this particular case.

What are your thoughts?

**Comment by HitmanInWis** [comment]
@davidjgonzalez As a followup to my comments above, if you feel an IM or phone conversation would be helpful, let me know and I'd be happy to further discuss.

**Comment by davidjgonzalez** [comment]
@HitmanInWis Mostly the visitor pattern is the Sling provided pattern for walking a tree. This also avoids the duplicative folder collecting work (which there is a different solution as we discussed) and lastly it avoids checking for containers. 
Anyhow - just a thought, instead of writing your own visitor.

**Comment by HitmanInWis** [comment]
Closed this out as the pull request is complete on the main project.

**Pull request closed without merging**
